import type { Priority } from "./types";

/**
 * Seed data for a new workspace.
 * a: 0 = Member 1 (Mansi), 1 = Member 2, 2 = Member 3, "everyone" = whole team.
 * Default due date = the phase end date (applied in seed.ts).
 */

type Assignee = 0 | 1 | 2 | "everyone";

export interface SeedTask {
  t: string;
  p?: Priority;
  a?: Assignee;
  tags?: string[];
}

export interface SeedPhase {
  number: number;
  name: string;
  description: string;
  start: string;
  end: string;
  /** default assignee for tasks without explicit assignee */
  a?: Assignee;
  /** default tags for tasks without explicit tags */
  tags?: string[];
  tasks: (string | SeedTask)[];
}

export const MEMBER_NAMES = ["Mansi", "Member 2", "Member 3"];

export const SEED_PHASES: SeedPhase[] = [
  {
    number: 0,
    name: "Team Setup",
    description: "Get the team aligned: names, roles, tools, and rituals.",
    start: "2026-10-03",
    end: "2026-10-03",
    a: "everyone",
    tasks: [
      { t: "Decide team name", p: "high" },
      { t: "Decide startup/project name", p: "high" },
      { t: "Assign team responsibilities", p: "high" },
      "Create team communication group",
      "Create shared Google Drive",
      { t: "Create GitHub repository", p: "high", a: 1, tags: ["Backend"] },
      "Create project management board",
      "Create shared decision document",
      { t: "Establish communication rules", p: "low" },
      "Establish standup schedule",
    ],
  },
  {
    number: 1,
    name: "Hackathon Understanding",
    description: "Read the rules inside out — know exactly how you'll be judged.",
    start: "2026-10-03",
    end: "2026-10-04",
    a: "everyone",
    tags: ["Research"],
    tasks: [
      { t: "Read complete hackathon rules", p: "high" },
      { t: "Read judging criteria", p: "high" },
      { t: "Identify required submission format", p: "high" },
      "Check technology restrictions",
      { t: "Identify AI requirements", p: "high", tags: ["Research", "AI"] },
      { t: "Identify mandatory features", p: "high" },
      "Identify presentation requirements",
      "Identify documentation requirements",
      { t: "Verify submission deadline", p: "critical" },
      "Verify time zone",
      { t: "Check whether deployment is required", p: "high" },
      "Check whether GitHub repository is required",
      "Check whether demo video is required",
      { t: "Create judging matrix", p: "high" },
    ],
  },
  {
    number: 2,
    name: "Problem Discovery",
    description: "Find a painful, frequent problem worth solving with AI.",
    start: "2026-10-04",
    end: "2026-10-06",
    a: 0,
    tags: ["Research"],
    tasks: [
      "Brainstorm 20–30 problems",
      "Categorize problems",
      "Identify repetitive tasks",
      "Identify decision-making problems",
      "Identify information overload problems",
      "Identify coordination problems",
      "Identify workflow problems",
      { t: "Identify problems where AI can take action", p: "high", tags: ["Research", "AI"] },
      "Shortlist top 10 problems",
      { t: "Score shortlisted problems", p: "high" },
      "Select top 5",
      "Research competitors",
      "Identify gaps",
      "Identify target users",
      "Evaluate problem severity",
      "Evaluate frequency of problem",
      "Evaluate willingness to use/pay",
      { t: "Select one core problem", p: "critical", a: "everyone" },
      { t: "Write problem statement", p: "high" },
      "Define target user",
    ],
  },
  {
    number: 3,
    name: "Solution Definition",
    description: "Shape the solution, the user, and the magic moment.",
    start: "2026-10-06",
    end: "2026-10-08",
    a: 0,
    tags: ["Research"],
    tasks: [
      { t: "Define product name", p: "high" },
      { t: "Define value proposition", p: "high" },
      "Define target customer",
      "Define user persona",
      { t: "Define core user journey", p: "high" },
      "Define main pain point",
      "Research existing alternatives",
      "Identify weaknesses in alternatives",
      { t: "Explain why AI is necessary", p: "high", tags: ["Research", "AI"] },
      { t: "Confirm the product is genuinely AI-first", p: "high", tags: ["Research", "AI"] },
      { t: 'Define the "magic moment"', p: "high" },
      "Define measurable user impact",
    ],
  },
  {
    number: 4,
    name: "Product Specification",
    description: "Turn the idea into a crisp spec: scope, requirements, MVP.",
    start: "2026-10-08",
    end: "2026-10-10",
    a: 0,
    tags: ["Documentation"],
    tasks: [
      { t: "Create PRD", p: "high" },
      { t: "Define functional requirements", p: "high" },
      { t: "Define AI requirements", p: "high", tags: ["Documentation", "AI"] },
      "Define inputs",
      "Define outputs",
      "Define integrations",
      "Define security requirements",
      { t: "Define performance expectations", p: "low" },
      { t: "Define MVP", p: "critical", a: "everyone" },
      { t: "Define MUST HAVE features", p: "critical", a: "everyone" },
      "Define SHOULD HAVE features",
      { t: "Define COULD HAVE features", p: "low" },
      { t: "Define features that will NOT be built", p: "low" },
    ],
  },
  {
    number: 5,
    name: "AI Architecture",
    description: "Design the AI system: models, agents, tools, and guardrails.",
    start: "2026-10-09",
    end: "2026-10-12",
    a: 0,
    tags: ["AI"],
    tasks: [
      { t: "Select AI model(s)", p: "critical" },
      { t: "Define AI architecture", p: "critical" },
      { t: "Decide agent architecture", p: "high" },
      { t: "Define prompting strategy", p: "high" },
      "Define tool usage",
      "Define memory requirements",
      "Define RAG requirements if needed",
      "Define data sources",
      "Define orchestration framework",
      { t: "Define APIs", p: "high", a: 1, tags: ["AI", "Backend"] },
      "Define fallback logic",
      { t: "Define hallucination protection", p: "high" },
      "Define human-in-the-loop requirements",
      { t: "Define AI evaluation metrics", p: "high" },
      { t: "Create architecture diagram", p: "high", tags: ["AI", "Documentation"] },
      "Create AI test cases",
    ],
  },
  {
    number: 6,
    name: "Technical Setup",
    description: "Repos, environments, deployment — the engineering foundation.",
    start: "2026-10-10",
    end: "2026-10-12",
    a: 1,
    tags: ["Backend"],
    tasks: [
      { t: "Create GitHub repository", p: "high" },
      { t: "Create project structure", p: "high" },
      "Create README",
      "Configure environment variables",
      { t: "Set up frontend", p: "high", a: 2, tags: ["Frontend"] },
      { t: "Set up backend", p: "high" },
      { t: "Set up database", p: "high" },
      { t: "Connect AI APIs", p: "high", tags: ["Backend", "AI"] },
      "Configure integrations",
      { t: "Configure deployment", p: "critical" },
      "Configure logging",
      "Configure error handling",
    ],
  },
  {
    number: 7,
    name: "MVP Development",
    description: "Build the MVP: backend, AI, frontend, and design together.",
    start: "2026-10-12",
    end: "2026-10-20",
    tasks: [
      // Backend
      { t: "API structure", p: "high", a: 1, tags: ["Backend"] },
      { t: "Database schema", p: "high", a: 1, tags: ["Backend"] },
      { t: "Core backend logic", p: "critical", a: 1, tags: ["Backend"] },
      { t: "Authentication only if necessary", p: "low", a: 1, tags: ["Backend"] },
      { t: "AI integration", p: "critical", a: 1, tags: ["Backend", "AI"] },
      { t: "Tool integrations", p: "high", a: 1, tags: ["Backend"] },
      { t: "Error handling", a: 1, tags: ["Backend"] },
      // AI
      { t: "System prompts", p: "high", a: 0, tags: ["AI"] },
      { t: "Agent workflows", p: "critical", a: 0, tags: ["AI"] },
      { t: "Tool calling", p: "critical", a: 0, tags: ["AI"] },
      { t: "Context management", p: "high", a: 0, tags: ["AI"] },
      { t: "Memory", a: 0, tags: ["AI"] },
      { t: "RAG", p: "high", a: 0, tags: ["AI"] },
      { t: "Output validation", p: "high", a: 0, tags: ["AI"] },
      { t: "AI evaluation", p: "high", a: 0, tags: ["AI"] },
      // Frontend
      { t: "Landing page", a: 2, tags: ["Frontend"] },
      { t: "Dashboard", p: "high", a: 2, tags: ["Frontend"] },
      { t: "Main workflow", p: "critical", a: 2, tags: ["Frontend"] },
      { t: "AI interaction", p: "high", a: 2, tags: ["Frontend", "AI"] },
      { t: "Results screen", p: "high", a: 2, tags: ["Frontend"] },
      { t: "Loading states", a: 2, tags: ["Frontend"] },
      { t: "Error states", a: 2, tags: ["Frontend"] },
      { t: "Empty states", a: 2, tags: ["Frontend"] },
      { t: "Responsive layout", a: 2, tags: ["Frontend"] },
      // Design
      { t: "Logo", a: 2, tags: ["Design"] },
      { t: "Typography", a: 2, tags: ["Design"] },
      { t: "UI system", a: 2, tags: ["Design"] },
      { t: "Icons", p: "low", a: 2, tags: ["Design"] },
      { t: "Colors", a: 2, tags: ["Design"] },
      { t: "Animations", p: "low", a: 2, tags: ["Design"] },
      { t: "Screenshots", a: 2, tags: ["Design"] },
    ],
  },
  {
    number: 8,
    name: "First Working Demo",
    description: "One end-to-end flow that works. Freeze the scope.",
    start: "2026-10-20",
    end: "2026-10-20",
    a: "everyone",
    tasks: [
      { t: "Complete end-to-end flow", p: "critical" },
      { t: "Verify AI functionality", p: "high", a: 0, tags: ["AI"] },
      { t: "Verify database", p: "high", a: 1, tags: ["Backend"] },
      { t: "Verify core feature", p: "critical" },
      { t: "Deploy product", p: "critical", a: 1, tags: ["Backend"] },
      { t: "Fix critical bugs", p: "critical" },
      { t: "Perform first complete demo", p: "high" },
      { t: "Freeze MVP scope", p: "critical" },
    ],
  },
  {
    number: 9,
    name: "Testing + Refinement",
    description: "Break it, fix it, refine it — functional, AI, and UX testing.",
    start: "2026-10-20",
    end: "2026-10-23",
    a: "everyone",
    tags: ["Testing"],
    tasks: [
      { t: "Functional testing", p: "high" },
      { t: "Browser testing", p: "high", a: 2 },
      { t: "Mobile testing", p: "high", a: 2 },
      "Slow internet testing",
      "Invalid input testing",
      { t: "API failure testing", p: "high", a: 1, tags: ["Testing", "Backend"] },
      { t: "AI failure testing", p: "high", a: 0, tags: ["Testing", "AI"] },
      { t: "Authentication testing if applicable", p: "low", a: 1 },
      { t: "Database failure testing", a: 1, tags: ["Testing", "Backend"] },
      { t: "AI accuracy testing", p: "high", a: 0, tags: ["Testing", "AI"] },
      { t: "AI consistency testing", a: 0, tags: ["Testing", "AI"] },
      { t: "Hallucination testing", p: "high", a: 0, tags: ["Testing", "AI"] },
      "Latency testing",
      "Cost testing",
      "Edge-case testing",
      { t: "User testing", p: "high" },
      { t: "Collect feedback", p: "high" },
      { t: "Fix major UX issues", p: "high", a: 2 },
      { t: "Fix major technical issues", p: "high", a: 1 },
      { t: "Remove unnecessary features", p: "low" },
    ],
  },
  {
    number: 10,
    name: "Startup Layer",
    description: "Name, brand, business model — make it a startup, not a demo.",
    start: "2026-10-23",
    end: "2026-10-25",
    a: 0,
    tags: ["Business"],
    tasks: [
      { t: "Finalize startup name", p: "high", a: "everyone" },
      { t: "Finalize logo", a: 2, tags: ["Business", "Design"] },
      "Finalize tagline",
      { t: "Define brand identity", a: 2, tags: ["Business", "Design"] },
      { t: "Build landing page", p: "high", a: 2, tags: ["Business", "Frontend"] },
      "Define target customers",
      "Define market",
      { t: "Define business model", p: "high" },
      "Define pricing concept",
      "Define acquisition strategy",
      "Research competition",
      { t: "Define differentiation", p: "high" },
      { t: "Define scalability", a: 1 },
      "Define future roadmap",
      { t: "Define measurable impact", p: "high" },
    ],
  },
  {
    number: 11,
    name: "Demo Engineering",
    description: "Engineer a bulletproof 2–3 minute demo.",
    start: "2026-10-24",
    end: "2026-10-26",
    a: "everyone",
    tags: ["Pitch"],
    tasks: [
      { t: "Create 2–3 minute demo", p: "critical" },
      { t: "Write demo script", p: "high", a: 0 },
      { t: "Prepare demo account", p: "high", a: 1 },
      { t: "Prepare sample data", p: "high", a: 1 },
      { t: "Create backup demo", p: "high", a: 1 },
      { t: "Capture screenshots", a: 2 },
      { t: "Record backup video", p: "high", a: 2 },
      { t: "Test demo flow", p: "high" },
      { t: "Practice live demonstration", p: "high" },
      "Prepare failure fallback",
    ],
  },
  {
    number: 12,
    name: "Pitch Deck",
    description: "Tell the story: the pitch deck that wins judges.",
    start: "2026-10-25",
    end: "2026-10-27",
    a: 0,
    tags: ["Pitch"],
    tasks: [
      { t: "Title slide", p: "high" },
      { t: "Problem slide", p: "high" },
      { t: "Why now slide", p: "high" },
      { t: "Solution slide", p: "high" },
      { t: "AI architecture slide", p: "high", tags: ["Pitch", "AI"] },
      { t: "Product slide", p: "high" },
      { t: "Impact slide", p: "high" },
      { t: "Business slide", p: "high" },
      "Competitive landscape",
      "Vision slide",
      { t: "Add product screenshots", a: 2, tags: ["Pitch", "Design"] },
      { t: "Finalize storytelling", p: "high", a: "everyone" },
      { t: "Finalize visual consistency", a: 2, tags: ["Pitch", "Design"] },
    ],
  },
  {
    number: 13,
    name: "Submission Documentation",
    description: "Everything submission needs: docs, links, screenshots.",
    start: "2026-10-27",
    end: "2026-10-28",
    a: 1,
    tags: ["Documentation"],
    tasks: [
      { t: "Project description", p: "high" },
      { t: "README", p: "critical" },
      { t: "Architecture diagram", p: "high" },
      "Tech stack",
      { t: "AI architecture", p: "high", a: 0, tags: ["Documentation", "AI"] },
      "Features",
      { t: "Installation instructions", p: "high" },
      { t: "Demo instructions", p: "high" },
      { t: "Deployment link", p: "critical" },
      { t: "GitHub link", p: "critical" },
      { t: "Screenshots", p: "high", a: 2 },
      "Team information",
      { t: "Business model", a: 0, tags: ["Documentation", "Business"] },
      { t: "Future roadmap", a: 0, tags: ["Documentation", "Business"] },
      { t: "Final documentation", p: "critical", a: "everyone" },
    ],
  },
  {
    number: 14,
    name: "Final QA",
    description: "Verify everything. Rehearse everything. Leave nothing to chance.",
    start: "2026-10-28",
    end: "2026-10-29",
    a: "everyone",
    tags: ["Testing"],
    tasks: [
      { t: "Verify production URL", p: "critical" },
      "Verify login if applicable",
      { t: "Verify main feature", p: "critical" },
      { t: "Verify AI", p: "critical", a: 0, tags: ["Testing", "AI"] },
      { t: "Verify APIs", p: "high", a: 1, tags: ["Testing", "Backend"] },
      { t: "Verify database", p: "high", a: 1, tags: ["Testing", "Backend"] },
      { t: "Fix critical bugs", p: "critical" },
      { t: "Test browser compatibility", a: 2 },
      { t: "Test mobile", a: 2 },
      { t: "Verify GitHub", p: "high", a: 1 },
      { t: "Verify demo URL", p: "high" },
      { t: "Verify video URL", p: "high" },
      { t: "Verify presentation", p: "high", a: 0 },
      { t: "Verify documentation", p: "high", a: 1 },
      { t: "Verify screenshots", a: 2 },
      "Verify team details",
      { t: "Complete final submission form", p: "critical", a: 0 },
      { t: "Perform final pitch rehearsal", p: "high", a: 0 },
      { t: "Perform final demo rehearsal", p: "high" },
      "Perform Q&A rehearsal",
    ],
  },
  {
    number: 15,
    name: "Final Submission",
    description: "Final checks, then hit submit. Ship it.",
    start: "2026-10-30",
    end: "2026-10-30",
    a: "everyone",
    tags: ["Business"],
    tasks: [
      { t: "Final production test", p: "critical", a: 1 },
      { t: "Final GitHub check", p: "high", a: 1 },
      { t: "Final documentation check", p: "high", a: 1 },
      { t: "Final demo check", p: "high" },
      { t: "Final presentation check", p: "high", a: 0 },
      { t: "Final video check", a: 2 },
      { t: "Verify every mandatory field", p: "critical", a: 0 },
      { t: "Submit project", p: "critical", a: 0 },
      { t: "Save confirmation screenshot", p: "high" },
      { t: "Save submission ID", p: "high", a: 0 },
      "Archive final project",
      { t: "Archive final deck", p: "low" },
      { t: "Archive final video", p: "low", a: 2 },
    ],
  },
];
