-- ============================================================================
-- HackSprint — demo workspace seed (generated by scripts/generate-seed-sql.ts)
-- Workspace ID: hs-53uu4q27p45k
-- Local URL:      http://localhost:3000/w/hs-53uu4q27p45k
-- Production URL: https://<your-app>.vercel.app/w/hs-53uu4q27p45k
-- Run AFTER supabase/migrations/0001_init.sql
-- ============================================================================

begin;

insert into workspaces (id, name, hackathon_name, deadline) values ('hs-53uu4q27p45k', 'HackSprint Workspace', 'AI Hackathon Sprint', '2026-10-30');

insert into team_members (id, workspace_id, name, avatar) values
  ('569f4405-6d27-4174-b30f-ddc1d4b4fe3c', 'hs-53uu4q27p45k', 'Mansi', 'v1'),
  ('1cdda910-c46c-444e-bb3e-e0f252b89504', 'hs-53uu4q27p45k', 'Member 2', 'v2'),
  ('85901fc1-b1fb-45ef-a9db-def1474184c3', 'hs-53uu4q27p45k', 'Member 3', 'v3');

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'hs-53uu4q27p45k', 0, 'Team Setup', 'Get the team aligned: names, roles, tools, and rituals.', '2026-10-03', '2026-10-03');
-- Phase 0: Team Setup
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('44ba98a5-fef7-4800-95c1-9e8d5c0b8b52', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Decide team name', 'high', 'everyone', '2026-10-03', '{}'::text[]),
  ('c423b84b-cdaa-4825-ba01-e9318b396376', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Decide startup/project name', 'high', 'everyone', '2026-10-03', '{}'::text[]),
  ('905a9afe-d60f-4521-b456-41efef03d74f', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Assign team responsibilities', 'high', 'everyone', '2026-10-03', '{}'::text[]),
  ('eaeee00f-3681-44b8-b56f-a39034b7d62e', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Create team communication group', 'medium', 'everyone', '2026-10-03', '{}'::text[]),
  ('571884da-a7f1-4058-a3be-b64b3e2feb82', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Create shared Google Drive', 'medium', 'everyone', '2026-10-03', '{}'::text[]),
  ('d6ea3282-09a3-47d9-808d-c70de519dee7', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Create GitHub repository', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-03', '{"Backend"}'::text[]),
  ('581f73a2-914a-4db4-bf13-90e7d2a19299', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Create project management board', 'medium', 'everyone', '2026-10-03', '{}'::text[]),
  ('237d9603-1a56-43ee-8af2-a12fc5626411', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Create shared decision document', 'medium', 'everyone', '2026-10-03', '{}'::text[]),
  ('a0585b79-0253-4247-94bc-4723429f5209', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Establish communication rules', 'low', 'everyone', '2026-10-03', '{}'::text[]),
  ('d084a5f5-74f6-4926-aca9-10c2f8d70044', 'hs-53uu4q27p45k', '666ebe70-d8dd-4a9b-9314-feecc31eab0b', 'Establish standup schedule', 'medium', 'everyone', '2026-10-03', '{}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'hs-53uu4q27p45k', 1, 'Hackathon Understanding', 'Read the rules inside out — know exactly how you''ll be judged.', '2026-10-03', '2026-10-04');
-- Phase 1: Hackathon Understanding
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('263786f0-f603-4384-aee4-3254f33ddb2f', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Read complete hackathon rules', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('c9f19b4f-00d7-461e-a0c4-2a3705dd7b4c', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Read judging criteria', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('b8a05838-a96c-45f0-8345-ef6c685409ac', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Identify required submission format', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('6cbcd570-c8db-4a4e-8a05-40b2e01b1905', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Check technology restrictions', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('569a5fa7-3045-4bba-9ec6-6adf11e50f25', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Identify AI requirements', 'high', 'everyone', '2026-10-04', '{"Research","AI"}'::text[]),
  ('bea5f3c6-1342-4c5e-ad30-5593f5f7441b', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Identify mandatory features', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('74dbe0ec-8d54-4770-89b1-16394ced04f5', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Identify presentation requirements', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('8a582d3d-acfd-4a09-ad01-b40311e40666', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Identify documentation requirements', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('d7cebc8b-f650-495f-adba-2fad3313a563', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Verify submission deadline', 'critical', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('7b932fbe-942f-40ae-9d1f-78017443cc54', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Verify time zone', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('dc56e183-3b3a-48fe-a4a3-5472f494692a', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Check whether deployment is required', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('18d502fc-ff74-4c4a-87dc-bc61efee03ed', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Check whether GitHub repository is required', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('762fc9e5-ff25-4e75-afb7-01d269082b47', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Check whether demo video is required', 'medium', 'everyone', '2026-10-04', '{"Research"}'::text[]),
  ('eb01616c-0da2-4692-8a7d-95b542fc150e', 'hs-53uu4q27p45k', 'e8f163a2-ce3a-4241-90b6-fe0a0c0c27f4', 'Create judging matrix', 'high', 'everyone', '2026-10-04', '{"Research"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'hs-53uu4q27p45k', 2, 'Problem Discovery', 'Find a painful, frequent problem worth solving with AI.', '2026-10-04', '2026-10-06');
-- Phase 2: Problem Discovery
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('dc3b55ea-6d20-4e56-a971-21b25c79e317', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Brainstorm 20–30 problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('ab5beb02-507b-4d75-8cd9-62112f951fa5', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Categorize problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('95f648c7-75b6-4ef3-848a-1c59b877b8b9', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify repetitive tasks', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('e940c99e-02a4-4d4e-bae8-318ba438ae32', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify decision-making problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('b5260581-1f0d-4120-b7e3-c81763ccbbcb', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify information overload problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('c2609dbb-8c52-4709-89cc-46602e8ff55e', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify coordination problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('488fe825-2e69-4a78-9e96-6afc6e562ab5', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify workflow problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('861c4a05-237c-47e3-a6ba-471e3610df5e', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify problems where AI can take action', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research","AI"}'::text[]),
  ('f2110890-9a9c-411f-aa5c-245d2008ff5e', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Shortlist top 10 problems', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('9056de7a-db8b-43a5-a69f-7cf96849b5ac', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Score shortlisted problems', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('dfc75509-a188-46f2-bb8b-d784c70d74bf', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Select top 5', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('d2d00eb4-19f4-49c6-a5f0-048a4ddf952f', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Research competitors', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('c745f118-b148-424d-8fce-b92ff56a01a3', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify gaps', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('18ebd15e-d600-4ece-9a4b-cb739a6745f6', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Identify target users', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('eb3537d6-8b82-47b4-927a-a5d27cea9d0c', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Evaluate problem severity', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('3c3b9726-ab60-4db7-90a9-f68d7eb8adb9', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Evaluate frequency of problem', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('a7035915-5009-41ee-9063-17c1b9ee0b24', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Evaluate willingness to use/pay', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('4bcebf57-b5dc-4b12-baef-d1725f3528bd', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Select one core problem', 'critical', 'everyone', '2026-10-06', '{"Research"}'::text[]),
  ('41139f8a-a909-49f6-944e-d207541662de', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Write problem statement', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]),
  ('038cb1ea-ce71-4423-806a-788bcfca3e89', 'hs-53uu4q27p45k', 'c3d3f94c-6327-40a3-9e87-ef709b0181d8', 'Define target user', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-06', '{"Research"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'hs-53uu4q27p45k', 3, 'Solution Definition', 'Shape the solution, the user, and the magic moment.', '2026-10-06', '2026-10-08');
-- Phase 3: Solution Definition
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('ee34428d-a9d8-4e7f-9311-ae044cabc463', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define product name', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('964e7067-f9f9-43ac-a0c5-7d120fbbde23', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define value proposition', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('d41a83cb-623d-48cb-9a50-9a8407336b45', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define target customer', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('ce0ec915-6b64-49c0-970f-603ed85dce45', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define user persona', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('806a9691-20cb-45f6-90fc-286045100571', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define core user journey', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('1b10bb30-d06a-480a-8f3e-ca2d7d7c11f6', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define main pain point', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('6b665ee3-4cdf-4e8c-877b-5fc42adfa59d', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Research existing alternatives', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('40684b57-2909-47cc-a9a0-f62d946ce60e', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Identify weaknesses in alternatives', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('4b1ec693-138f-4c02-a5a4-de54d566a01b', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Explain why AI is necessary', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research","AI"}'::text[]),
  ('43fc3e1e-64f2-4e2c-bb91-c26e4b401d65', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Confirm the product is genuinely AI-first', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research","AI"}'::text[]),
  ('a05668b0-4cff-4e18-a40d-fcd2b4cf7119', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define the "magic moment"', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]),
  ('de1dd73b-4278-496d-90ac-b2301a26f2df', 'hs-53uu4q27p45k', 'bd96ddff-cc79-4f07-80cb-2cfe84620c3d', 'Define measurable user impact', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-08', '{"Research"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'hs-53uu4q27p45k', 4, 'Product Specification', 'Turn the idea into a crisp spec: scope, requirements, MVP.', '2026-10-08', '2026-10-10');
-- Phase 4: Product Specification
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('6a4dc43a-ebcb-495b-b4a7-ae81a8b6dea1', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Create PRD', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('046d845f-8cf8-4b5b-a66d-442e5572e97b', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define functional requirements', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('c2cf241e-33a4-4a32-8d5b-9f4896b5f536', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define AI requirements', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation","AI"}'::text[]),
  ('1135af6b-eeda-4935-a074-d6603c76a842', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define inputs', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('43daa4f8-b14e-45b2-8b63-31b153208779', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define outputs', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('da295a87-7d4e-4fd0-ba15-18022a2cd6d9', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define integrations', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('2f3da5e0-7517-425d-b1b6-5203eb836ebc', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define security requirements', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('a73a355b-2703-4c0b-a015-846a26ef852d', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define performance expectations', 'low', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('9247d733-c463-4d52-a318-3be54085644f', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define MVP', 'critical', 'everyone', '2026-10-10', '{"Documentation"}'::text[]),
  ('2d52b80e-e422-4fe4-8d7c-7b13281904ef', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define MUST HAVE features', 'critical', 'everyone', '2026-10-10', '{"Documentation"}'::text[]),
  ('9c6f98ef-1fe3-44dc-9899-63fa7bd7023e', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define SHOULD HAVE features', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('73a7f428-cee4-43dd-a11e-06d3f4e58003', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define COULD HAVE features', 'low', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]),
  ('7a20d4f4-efa1-4db8-810c-4503405d767d', 'hs-53uu4q27p45k', '1645b7b2-ce50-44a2-998a-d15197e0ccb0', 'Define features that will NOT be built', 'low', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-10', '{"Documentation"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'hs-53uu4q27p45k', 5, 'AI Architecture', 'Design the AI system: models, agents, tools, and guardrails.', '2026-10-09', '2026-10-12');
-- Phase 5: AI Architecture
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('89996a72-b5f4-465b-8be1-5bbe71b4cf06', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Select AI model(s)', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('a925287b-7ffc-462f-88d7-e8323933ff5a', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define AI architecture', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('f064f485-1874-499e-809d-07120775e0a1', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Decide agent architecture', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('5e2b137f-052f-4844-9c80-0383b9bf4c89', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define prompting strategy', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('37acbbf0-c020-479f-a179-7fcd517318cc', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define tool usage', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('2588562b-0d97-4beb-b437-abf30268b28d', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define memory requirements', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('75ea3bd2-33c3-468e-9554-626793a3dad6', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define RAG requirements if needed', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('7bc2a61e-9a15-46e6-bd73-ed8e5a1e0e4a', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define data sources', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('f85baee8-dc40-4314-9f5a-50d1a4a0269c', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define orchestration framework', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('64ed02fd-868d-4f2c-a7d3-2a69596db4e5', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define APIs', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"AI","Backend"}'::text[]),
  ('461b4ca4-f64d-47e3-8ee3-fe1dd858ffcf', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define fallback logic', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('d594384c-ddf3-4c13-9b93-9a0a8416967d', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define hallucination protection', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('b26a53e3-03a4-4219-8605-459c5a383e2b', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define human-in-the-loop requirements', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('09066a95-a005-4404-b92c-506762b56ddf', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Define AI evaluation metrics', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]),
  ('b01e02fa-7b55-40de-84b5-6b394dfe67c1', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Create architecture diagram', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI","Documentation"}'::text[]),
  ('5b2d61a8-59ca-4179-b633-6c348ff05f0e', 'hs-53uu4q27p45k', '85d7eced-4e6c-4e7c-baa3-f4449d4199af', 'Create AI test cases', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-12', '{"AI"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'hs-53uu4q27p45k', 6, 'Technical Setup', 'Repos, environments, deployment — the engineering foundation.', '2026-10-10', '2026-10-12');
-- Phase 6: Technical Setup
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('3bb233b9-eaa9-4e01-ac52-9267a0a79798', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Create GitHub repository', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('d4e7b9fc-970b-496b-8571-4b6c3d1fa569', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Create project structure', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('a6264a29-cab8-485a-88de-c73dd0fa0c77', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Create README', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('13760456-f856-49c8-983d-a105e553d0a6', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Configure environment variables', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('7142ae35-24d2-4602-a74f-cc6acf62ea92', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Set up frontend', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-12', '{"Frontend"}'::text[]),
  ('4426377b-b7cc-4bdf-a572-b5ba1f7d7dd6', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Set up backend', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('86bd6f4a-d10e-4e5d-b7e1-c9cf83a4dcff', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Set up database', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('f10ee63b-716a-49cd-9b8d-6e7e1c9e803a', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Connect AI APIs', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend","AI"}'::text[]),
  ('5fdc3750-adb7-4314-86b3-d4038f40031f', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Configure integrations', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('a347da0b-a2ab-47fd-bbbd-3dd75f2b175c', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Configure deployment', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('830786e3-7195-48a9-93f8-6886692cdf1b', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Configure logging', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]),
  ('46e3b265-9525-4e85-881c-c8f9c3971a74', 'hs-53uu4q27p45k', '0c5a9a60-40de-4b05-bf75-0c23967f39d6', 'Configure error handling', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-12', '{"Backend"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('15c16e90-4baa-4e53-8cf4-0933c6199751', 'hs-53uu4q27p45k', 7, 'MVP Development', 'Build the MVP: backend, AI, frontend, and design together.', '2026-10-12', '2026-10-20');
-- Phase 7: MVP Development
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('efbd4572-f7e5-47d3-8ce5-d5ebdb025d0c', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'API structure', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('f915ac38-ced0-4cdb-a9ea-f05f28aca351', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Database schema', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('96d82289-d368-403e-928a-ef993f5e981f', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Core backend logic', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('2bdc1514-a9e0-400e-b36c-0b21ba73f984', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Authentication only if necessary', 'low', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('eecddf30-7166-4e3c-800e-a4372a318f12', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'AI integration', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend","AI"}'::text[]),
  ('f8ba7c60-34a3-4ab9-af00-bb87256db785', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Tool integrations', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('8dfa8b33-4c8f-43ca-a6fa-946523684ead', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Error handling', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('b78c1d64-3c77-42b3-93e8-0d667ecf594b', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'System prompts', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('b9a86540-2a31-470b-98f2-651897dfd413', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Agent workflows', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('4d4aaa20-37c8-45c4-81e6-5cdf5a1f0ac9', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Tool calling', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('2ff9d81f-7c79-4e1a-a085-9977a462d61f', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Context management', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('6868183f-7d87-4853-8cc1-827be9098302', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Memory', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('a6531d76-dbeb-45e3-8c32-e84077bcddab', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'RAG', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('a15e043a-742f-423f-a968-5822250cac30', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Output validation', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('5fabf79b-11b0-422f-aa5a-ef2eb4aa311e', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'AI evaluation', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('a6018c44-b996-4839-8c5c-8d0e8170fcfd', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Landing page', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('1a4706df-0a9a-4469-af6b-9de4d7f8e088', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Dashboard', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('1577bc13-50fe-466f-a048-0b22c6e60ebf', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Main workflow', 'critical', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('e0c0e5b7-2bac-492b-8951-541827057f5b', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'AI interaction', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend","AI"}'::text[]),
  ('762cacd0-90c5-44b5-8b1a-735640973438', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Results screen', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('9b4defff-c124-4597-a399-48f2f5e08f09', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Loading states', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('6dcdd5f9-a74c-45cf-ad6f-cef74908d978', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Error states', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('63d0ea72-18e9-458e-84e5-97337e7400c0', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Empty states', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('f2fa7abf-608a-4297-84fc-5312b20f6d4c', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Responsive layout', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Frontend"}'::text[]),
  ('11c7d3b8-af75-4c9f-9000-d5b7526b13dc', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Logo', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('97707ca2-653d-4a48-8849-efd414876c16', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Typography', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('0b71dccf-b72a-4a01-8e19-a9a2029bbd4e', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'UI system', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('18ff2974-21aa-4306-916b-57975d9b81be', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Icons', 'low', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('64419f2d-9775-475e-b539-7ec2239f2508', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Colors', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('03d2b510-04c2-4408-b599-9e73970f4847', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Animations', 'low', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]),
  ('f42ea7fc-3793-4fd4-82dc-b0cdc2aeb4f1', 'hs-53uu4q27p45k', '15c16e90-4baa-4e53-8cf4-0933c6199751', 'Screenshots', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-20', '{"Design"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('e744fd68-745e-4049-af3b-4e7ab1f04b59', 'hs-53uu4q27p45k', 8, 'First Working Demo', 'One end-to-end flow that works. Freeze the scope.', '2026-10-20', '2026-10-20');
-- Phase 8: First Working Demo
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('1eaf15f3-53c9-4318-90ab-b1eb560521b7', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Complete end-to-end flow', 'critical', 'everyone', '2026-10-20', '{}'::text[]),
  ('403e0ec0-24bd-46f1-b590-4d5362815a6b', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Verify AI functionality', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-20', '{"AI"}'::text[]),
  ('9d54d86d-ae61-48f0-bd7c-0fd1bc49e8dc', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Verify database', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('0fac6ca9-beb1-43fe-919f-edc4494fb633', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Verify core feature', 'critical', 'everyone', '2026-10-20', '{}'::text[]),
  ('2b8f57f8-aa28-4a4c-b14f-1054a8b0d670', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Deploy product', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-20', '{"Backend"}'::text[]),
  ('0ebf415c-332c-475c-993f-4da637d2f0cd', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Fix critical bugs', 'critical', 'everyone', '2026-10-20', '{}'::text[]),
  ('a476b634-7f52-4738-b919-f262582f1409', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Perform first complete demo', 'high', 'everyone', '2026-10-20', '{}'::text[]),
  ('1592766a-14f0-4b30-b081-b85c8bb6a8a9', 'hs-53uu4q27p45k', 'e744fd68-745e-4049-af3b-4e7ab1f04b59', 'Freeze MVP scope', 'critical', 'everyone', '2026-10-20', '{}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'hs-53uu4q27p45k', 9, 'Testing + Refinement', 'Break it, fix it, refine it — functional, AI, and UX testing.', '2026-10-20', '2026-10-23');
-- Phase 9: Testing + Refinement
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('d9df560b-9e60-459d-b212-c3e8f90ac89c', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Functional testing', 'high', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('ee3059db-72b5-4f5d-b321-1e0a1976f4b6', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Browser testing', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-23', '{"Testing"}'::text[]),
  ('30841453-2289-4eaf-ba6f-66d836c9cf9d', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Mobile testing', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-23', '{"Testing"}'::text[]),
  ('a7638d58-caa5-466f-8bef-5b9a4e421ddf', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Slow internet testing', 'medium', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('431dc582-d387-4777-adcb-f4ca09f9c412', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Invalid input testing', 'medium', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('a1754c5a-4ddc-4b6a-beda-9fbb99da4117', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'API failure testing', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-23', '{"Testing","Backend"}'::text[]),
  ('42f3d570-fccf-485f-925a-8dad69927d81', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'AI failure testing', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-23', '{"Testing","AI"}'::text[]),
  ('50dffae0-d170-4ca3-ac55-914b9872d6d6', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Authentication testing if applicable', 'low', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-23', '{"Testing"}'::text[]),
  ('020ee584-9e12-469e-afb1-efe0867757a9', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Database failure testing', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-23', '{"Testing","Backend"}'::text[]),
  ('88dc5d96-abab-4e8c-9605-b3259bdd2acd', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'AI accuracy testing', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-23', '{"Testing","AI"}'::text[]),
  ('a55a9941-4ff5-4f60-86a4-d079f1e78cc8', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'AI consistency testing', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-23', '{"Testing","AI"}'::text[]),
  ('9d16baf9-601d-46c8-90e5-78cc144c0693', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Hallucination testing', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-23', '{"Testing","AI"}'::text[]),
  ('207a2f6e-8770-4121-b57e-dc1db67454c8', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Latency testing', 'medium', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('cca13ec9-8390-4719-9120-adbe72576f46', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Cost testing', 'medium', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('fea56e7f-0225-4b99-ad40-dafb8ec741ed', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Edge-case testing', 'medium', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('1990e1bf-8ee7-43e7-8f72-501e6eb40858', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'User testing', 'high', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('ed9929ec-b6e8-4799-bdf4-1dfc19411769', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Collect feedback', 'high', 'everyone', '2026-10-23', '{"Testing"}'::text[]),
  ('573d353b-56ab-498f-9628-dc1b5ea610ea', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Fix major UX issues', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-23', '{"Testing"}'::text[]),
  ('23b39874-e8bb-4f11-894c-e61a7614bd72', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Fix major technical issues', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-23', '{"Testing"}'::text[]),
  ('41c81937-1fab-418b-a598-ab7dbc2b16be', 'hs-53uu4q27p45k', '4519f6b3-37a1-43bc-ab19-9cef8725cac5', 'Remove unnecessary features', 'low', 'everyone', '2026-10-23', '{"Testing"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'hs-53uu4q27p45k', 10, 'Startup Layer', 'Name, brand, business model — make it a startup, not a demo.', '2026-10-23', '2026-10-25');
-- Phase 10: Startup Layer
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('292265de-04d4-4cfc-82f6-de2fe819d5b5', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Finalize startup name', 'high', 'everyone', '2026-10-25', '{"Business"}'::text[]),
  ('7a8478eb-3bde-49e8-9813-40097d0b8db5', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Finalize logo', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-25', '{"Business","Design"}'::text[]),
  ('5d95db28-68ae-418c-bea4-07d12ab5eb3d', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Finalize tagline', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('ae1165ae-0ebf-4f21-91e0-6097a99f41a1', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define brand identity', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-25', '{"Business","Design"}'::text[]),
  ('a86b0b4f-cd10-4067-b82d-8f67f8196681', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Build landing page', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-25', '{"Business","Frontend"}'::text[]),
  ('ce6447fb-89e9-409e-902d-e718845a2baa', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define target customers', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('72904c07-ee9d-4915-a207-a8933e63438c', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define market', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('3e76e204-5f87-4060-8d67-c27cd09d8045', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define business model', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('7a177086-4750-49f6-956b-f96711c4051e', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define pricing concept', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('9de53c08-a9c4-4059-b26d-5d961fb6aae0', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define acquisition strategy', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('3dbc1537-4472-4664-aef3-3c86d41ac9cc', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Research competition', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('3f549005-8387-4097-a72e-5130e97062a0', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define differentiation', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('aec59e14-93d7-4267-89ba-887bb853aa23', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define scalability', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-25', '{"Business"}'::text[]),
  ('b1e257ff-a846-484f-be37-1a2a142f3b0f', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define future roadmap', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]),
  ('c6c1131a-b417-4db4-84b0-1ff50a9daa4c', 'hs-53uu4q27p45k', 'fffd2b7f-4e42-442d-96a2-d9d39adc60c7', 'Define measurable impact', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-25', '{"Business"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('51cf5c72-a5fb-436e-866a-b993f2660236', 'hs-53uu4q27p45k', 11, 'Demo Engineering', 'Engineer a bulletproof 2–3 minute demo.', '2026-10-24', '2026-10-26');
-- Phase 11: Demo Engineering
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('bb3bea0e-2cf3-47da-b3ff-eb682c91dbfe', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Create 2–3 minute demo', 'critical', 'everyone', '2026-10-26', '{"Pitch"}'::text[]),
  ('1b3d496b-5674-4d49-8e65-80ddf56f6e43', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Write demo script', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-26', '{"Pitch"}'::text[]),
  ('f1fdb185-6b1b-4dcd-93a1-1820425fa8b5', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Prepare demo account', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-26', '{"Pitch"}'::text[]),
  ('e6e861ee-3e03-4a95-9b6d-127cf1f7c814', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Prepare sample data', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-26', '{"Pitch"}'::text[]),
  ('76df7934-4561-4a65-92cd-f368b61b1b33', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Create backup demo', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-26', '{"Pitch"}'::text[]),
  ('93a03dbd-2aba-4830-bef9-876917978ac8', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Capture screenshots', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-26', '{"Pitch"}'::text[]),
  ('cc1d1f9b-3107-42cc-b59d-6d45d47883f8', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Record backup video', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-26', '{"Pitch"}'::text[]),
  ('9d6c4cf3-0ec2-4c9a-b1f1-fd2428ec056c', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Test demo flow', 'high', 'everyone', '2026-10-26', '{"Pitch"}'::text[]),
  ('56d68786-f8aa-4a44-8369-a5e5f90fa059', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Practice live demonstration', 'high', 'everyone', '2026-10-26', '{"Pitch"}'::text[]),
  ('0b556d4a-e842-4e68-86bb-3e5bb87d7d65', 'hs-53uu4q27p45k', '51cf5c72-a5fb-436e-866a-b993f2660236', 'Prepare failure fallback', 'medium', 'everyone', '2026-10-26', '{"Pitch"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('e1bf6b89-8d24-4bb8-b485-8b798993b661', 'hs-53uu4q27p45k', 12, 'Pitch Deck', 'Tell the story: the pitch deck that wins judges.', '2026-10-25', '2026-10-27');
-- Phase 12: Pitch Deck
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('310637b8-863b-4654-a30e-487843f9c702', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Title slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('0cae8c70-b00d-40a1-a378-d85d197efcc3', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Problem slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('7859ce64-4bd2-44a7-9d0f-272484d2f598', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Why now slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('a6d1db9e-97c6-4469-a70c-25fddda7c9e9', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Solution slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('11bd61b2-4066-4e1e-8827-388fee0e95a7', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'AI architecture slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch","AI"}'::text[]),
  ('3d2a9b8f-065b-4ad9-8b7d-6ac523dab9eb', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Product slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('2902802e-9175-449d-b391-aae0f862f093', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Impact slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('cd38f41b-5ae0-4d56-ba5d-12ee257de410', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Business slide', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('4007ca69-94d4-4506-a8f0-dcf2a0700bab', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Competitive landscape', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('9d900cbe-1f6b-44af-a8da-12737dbb39f1', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Vision slide', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-27', '{"Pitch"}'::text[]),
  ('eebcc807-09fc-41c3-97ad-ec7891b350d1', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Add product screenshots', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-27', '{"Pitch","Design"}'::text[]),
  ('ccaf4097-d662-4156-be2a-7fc4339a275f', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Finalize storytelling', 'high', 'everyone', '2026-10-27', '{"Pitch"}'::text[]),
  ('3bfd3afd-b72c-4610-93ba-8823b348dadb', 'hs-53uu4q27p45k', 'e1bf6b89-8d24-4bb8-b485-8b798993b661', 'Finalize visual consistency', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-27', '{"Pitch","Design"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('e55e015f-2033-46c6-865a-f5a165e69610', 'hs-53uu4q27p45k', 13, 'Submission Documentation', 'Everything submission needs: docs, links, screenshots.', '2026-10-27', '2026-10-28');
-- Phase 13: Submission Documentation
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('6c0ef793-c1d7-4bf4-b490-ed04ff20330e', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Project description', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('5fe6c646-6d4e-4030-9c0d-be3e37852e46', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'README', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('519c021b-d419-41e7-898d-b0c337bdac39', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Architecture diagram', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('aaaed064-0c1a-4245-920b-5961bcc13af5', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Tech stack', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('dc9a8c2a-f326-4a87-8430-6dce257d4ec9', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'AI architecture', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-28', '{"Documentation","AI"}'::text[]),
  ('84ca5674-22de-48f3-b648-0995327a7bad', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Features', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('b44104f9-0f95-448b-8776-52e095e2fc0e', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Installation instructions', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('3383595b-6fac-40df-8be9-f92660dea8ea', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Demo instructions', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('8f6dde50-703b-412c-836c-f35dc309c934', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Deployment link', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('e58c083e-9dcd-436e-9d9a-b63783685131', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'GitHub link', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('bbd100e1-525c-4bc8-88a9-97c405fddc8f', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Screenshots', 'high', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-28', '{"Documentation"}'::text[]),
  ('11c051d1-be45-498e-af46-9b96887924df', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Team information', 'medium', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-28', '{"Documentation"}'::text[]),
  ('afc9cf84-847b-48b4-b1a8-af3db426b256', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Business model', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-28', '{"Documentation","Business"}'::text[]),
  ('0e10562e-2674-4019-b80e-610cc31d5e76', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Future roadmap', 'medium', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-28', '{"Documentation","Business"}'::text[]),
  ('6fd3d27b-f5ee-4b59-86ce-504a0b877fa5', 'hs-53uu4q27p45k', 'e55e015f-2033-46c6-865a-f5a165e69610', 'Final documentation', 'critical', 'everyone', '2026-10-28', '{"Documentation"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'hs-53uu4q27p45k', 14, 'Final QA', 'Verify everything. Rehearse everything. Leave nothing to chance.', '2026-10-28', '2026-10-29');
-- Phase 14: Final QA
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('fa705f14-ac0b-465e-b752-13669cc50ec2', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify production URL', 'critical', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('429b91d2-3701-4d15-929c-b502ce7d5261', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify login if applicable', 'medium', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('ae1d70d9-1e51-4d7e-a902-bf5538ff56af', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify main feature', 'critical', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('579574d7-39c9-4eb9-aa41-0911c638bd5a', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify AI', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-29', '{"Testing","AI"}'::text[]),
  ('5197ffe6-0e5b-4d61-bd69-92415edce5e1', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify APIs', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-29', '{"Testing","Backend"}'::text[]),
  ('d503552e-6fb8-4383-803c-408dd99d028a', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify database', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-29', '{"Testing","Backend"}'::text[]),
  ('fa5e7bda-8e72-4979-99ad-ed80226986a8', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Fix critical bugs', 'critical', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('51e51f63-5b1f-4854-8426-df55444b1fb9', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Test browser compatibility', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-29', '{"Testing"}'::text[]),
  ('888a8e69-5d65-4d0f-b7cf-6c4bf51500bc', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Test mobile', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-29', '{"Testing"}'::text[]),
  ('56bf93a6-db1f-4464-a54b-42c57232d024', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify GitHub', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-29', '{"Testing"}'::text[]),
  ('8c5c501f-d532-4c9a-b305-06b9b7e92da4', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify demo URL', 'high', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('10f39962-95d0-4134-bdb9-600239c14071', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify video URL', 'high', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('90fa06bf-dd24-48bd-97e6-c0c186f125a7', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify presentation', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-29', '{"Testing"}'::text[]),
  ('f371eb13-45a1-40df-8d94-27f06c9ce63f', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify documentation', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-29', '{"Testing"}'::text[]),
  ('7dcbb04b-c805-4323-9877-6825fc9e5b61', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify screenshots', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-29', '{"Testing"}'::text[]),
  ('1decb937-0610-48db-9b57-4ca8acf122fa', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Verify team details', 'medium', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('2d621022-fc50-4705-a135-df85c52128a6', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Complete final submission form', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-29', '{"Testing"}'::text[]),
  ('45b42465-c458-430c-b523-f0403fa9e9dc', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Perform final pitch rehearsal', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-29', '{"Testing"}'::text[]),
  ('f6ba8bbe-59c1-4e6c-b1c3-c1bd1dc70c49', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Perform final demo rehearsal', 'high', 'everyone', '2026-10-29', '{"Testing"}'::text[]),
  ('d41d75bc-29a9-4500-80f9-7cea655ea5d9', 'hs-53uu4q27p45k', 'b0c80ef6-3cec-4fe5-8f63-b6abecb59332', 'Perform Q&A rehearsal', 'medium', 'everyone', '2026-10-29', '{"Testing"}'::text[]);

insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values ('e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'hs-53uu4q27p45k', 15, 'Final Submission', 'Final checks, then hit submit. Ship it.', '2026-10-30', '2026-10-30');
-- Phase 15: Final Submission
insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values
  ('5d8280a9-a75e-4317-bc42-40633a23d570', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final production test', 'critical', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-30', '{"Business"}'::text[]),
  ('25a13f0b-a5ba-432b-8dcc-483f5ab0defd', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final GitHub check', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-30', '{"Business"}'::text[]),
  ('67696107-95c7-43e2-b9ec-783e29465744', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final documentation check', 'high', '1cdda910-c46c-444e-bb3e-e0f252b89504', '2026-10-30', '{"Business"}'::text[]),
  ('85c4149d-6f04-494c-8a1a-b7392f83254b', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final demo check', 'high', 'everyone', '2026-10-30', '{"Business"}'::text[]),
  ('427a9708-0bf2-49f2-bcc8-16c54e5617ad', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final presentation check', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-30', '{"Business"}'::text[]),
  ('73b81e16-7890-4444-afd5-442a1f23a2a6', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Final video check', 'medium', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-30', '{"Business"}'::text[]),
  ('f1dddc09-82be-4f4e-b2ec-3099223858bd', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Verify every mandatory field', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-30', '{"Business"}'::text[]),
  ('77598b6d-c783-40b5-89aa-398d590607e5', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Submit project', 'critical', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-30', '{"Business"}'::text[]),
  ('06e1896c-4fa5-4c18-b66f-d1fec2fa1770', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Save confirmation screenshot', 'high', 'everyone', '2026-10-30', '{"Business"}'::text[]),
  ('1279bc18-892a-4209-886c-0cde01a5eaca', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Save submission ID', 'high', '569f4405-6d27-4174-b30f-ddc1d4b4fe3c', '2026-10-30', '{"Business"}'::text[]),
  ('07e4def9-ec7b-451f-8ebc-3455f96c34e8', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Archive final project', 'medium', 'everyone', '2026-10-30', '{"Business"}'::text[]),
  ('d2eb01d7-19e7-4397-9b31-d5628dd5903a', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Archive final deck', 'low', 'everyone', '2026-10-30', '{"Business"}'::text[]),
  ('13e7fe30-69f1-47ad-9c9c-3f75707d9fbd', 'hs-53uu4q27p45k', 'e6cd9961-cc49-47e2-b152-3c2c2ce95826', 'Archive final video', 'low', '85901fc1-b1fb-45ef-a9db-def1474184c3', '2026-10-30', '{"Business"}'::text[]);

commit;
