/**
 * Generates supabase/seed.sql — a fully seeded demo workspace for Supabase.
 * Run: npx tsx scripts/generate-seed-sql.ts
 */
import { randomUUID } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { MEMBER_NAMES, SEED_PHASES } from "../src/lib/seed-data";

const __dirname = dirname(fileURLToPath(import.meta.url));

const alphabet = "abcdefghijkmnpqrstuvwxyz23456789";
const slug = `hs-${Array.from({ length: 12 }, () => alphabet[Math.floor(Math.random() * alphabet.length)]).join("")}`;

const esc = (s: string) => s.replace(/'/g, "''");
const lit = (s: string) => `'${esc(s)}'`;

const members = MEMBER_NAMES.map((name, i) => ({
  id: randomUUID(),
  name,
  avatar: `v${i + 1}`,
}));

const lines: string[] = [];
lines.push("-- ============================================================================");
lines.push("-- HackSprint — demo workspace seed (generated by scripts/generate-seed-sql.ts)");
lines.push(`-- Workspace ID: ${slug}`);
lines.push(`-- Local URL:      http://localhost:3000/w/${slug}`);
lines.push(`-- Production URL: https://<your-app>.vercel.app/w/${slug}`);
lines.push("-- Run AFTER supabase/migrations/0001_init.sql");
lines.push("-- ============================================================================");
lines.push("");
lines.push("begin;");
lines.push("");
lines.push(
  `insert into workspaces (id, name, hackathon_name, deadline) values (${lit(slug)}, 'HackSprint Workspace', 'AI Hackathon Sprint', '2026-10-30');`,
);
lines.push("");
lines.push("insert into team_members (id, workspace_id, name, avatar) values");
lines.push(
  members.map((m) => `  (${lit(m.id)}, ${lit(slug)}, ${lit(m.name)}, ${lit(m.avatar)})`).join(",\n") + ";",
);
lines.push("");

for (const phase of SEED_PHASES) {
  const phaseId = randomUUID();
  lines.push(
    `insert into phases (id, workspace_id, phase_number, name, description, start_date, end_date) values (${lit(phaseId)}, ${lit(slug)}, ${phase.number}, ${lit(phase.name)}, ${lit(phase.description)}, ${lit(phase.start)}, ${lit(phase.end)});`,
  );
  const rows = phase.tasks.map((raw) => {
    const task = typeof raw === "string" ? { t: raw } : raw;
    const a = task.a ?? phase.a ?? "everyone";
    const assignee = a === "everyone" ? "everyone" : members[a].id;
    const tags = (task.tags ?? phase.tags ?? []).map((t) => `"${t}"`).join(",");
    return `  (${lit(randomUUID())}, ${lit(slug)}, ${lit(phaseId)}, ${lit(task.t)}, ${lit(task.p ?? "medium")}, ${lit(assignee)}, ${lit(phase.end)}, '{${tags}}'::text[])`;
  });
  lines.push(`-- Phase ${phase.number}: ${phase.name}`);
  lines.push(
    "insert into tasks (id, workspace_id, phase_id, title, priority, assigned_to, due_date, tags) values",
  );
  lines.push(rows.join(",\n") + ";");
  lines.push("");
}

lines.push("commit;");
lines.push("");

const out = join(__dirname, "..", "supabase", "seed.sql");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}`);
console.log(`Workspace ID: ${slug}`);
